beh_vine_impl:
; BHV_START OBJ_LIST_MAGNETIC
BHV_OR_FLAGS o_flags, OBJ_FLAG_UPDATE_GFX
BHV_SET_INTERACTION INT_POLE
BHV_SET_HITBOX 160, 1000, 0
BHV_SET_INT o_intangibility_timer, 0
BHV_SET_FLOAT o_render_distance, 9000
BHV_LOOP_BEGIN
	BHV_EXEC horizontally_billboard
	BHV_EXEC 0x802C63E8
BHV_LOOP_END
