/*
This skeleton was autogenerated by Bowser's Blueprints. It will NOT be replaced
on rebuilding, so you are free to modify this file.

Do NOT use the .org, .orga, or .headersize commands in this file or files
included by this file. Anything that needs to write to elsewhere in the ROM
should go into globals.asm instead.

This file is intended to be used for global behaviour scripts. You can
implement the main part of your behaviour scripts (everything except the first
0x00 command) in another file linked using misc-injected.asm, then reference
that behaviour script in this file using the @link_behaviour macro provided
below (or @link_behaviour_segmented if you are using a segmented address).
*/

; Object Lists
.definelabel @EXPLOSION, 0x2 ; things that can damage other objects (bombs, explosions, and bouncy cork boxes)
.definelabel @GENERIC, 0x4 ; objects that can have hitbox collisions with explosions (@INTERACTIVE and @SURFACE also collide with explosions)
.definelabel @INTERACTIVE, 0x5 ; objects that can detect hitbox collisions with other objects (not just Mario!)
.definelabel @LEVEL, 0x6 ; nothing too special about this list. Has hitbox collision, but only checks for collisions with Mario
.definelabel @DEFAULT, 0x8 ; where objects without an object list explicitly set go. Does not process collision
.definelabel @SURFACE, 0x9 ; objects with triangle collision
.definelabel @MAGNETIC, 0xA ; objects that Mario can climb (poles/trees) or that pull him in (tornado/whirlpool) or push him (wind)
.definelabel @SPAWNER, 0xB ; objects that spawn other objects. Objects in this list get processed first
.definelabel @PARTICLES, 0xC ; unimportant objects that will get automatically despawned if more important objects need to load

.macro @link_behaviour_segmented, objectList, segmentedAddress
	.byte 0x00, objectList, 0x00, 0x00
	.word 0x04000000, segmentedAddress
.endmacro

.macro @link_behaviour, objectList, virtualAddress
	@link_behaviour_segmented objectList, (virtualAddress - 0x80000000)
.endmacro

; Link your behaviour scripts here. They will start at segmented address
; 0x00367500 and increase by 0xC (12) for each additional behaviour.


; 0x00367500
@link_behaviour @DEFAULT, beh_warp_star_landing_impl

; 0x0036750C
.definelabel beh_super_shroom, (org() - 0x80000000)
@link_behaviour @LEVEL, beh_super_shroom_impl

; 0x00367518
.definelabel beh_ultra_shroom, (org() - 0x80000000)
@link_behaviour @LEVEL, beh_ultra_shroom_impl

; 0x00367524
.definelabel beh_golden_shroom, (org() - 0x80000000)
@link_behaviour @LEVEL, beh_golden_shroom_impl

; 0x00367530
@link_behaviour @LEVEL, beh_tree_impl

; 0x0036753C
@link_behaviour @LEVEL, beh_ghost_impl

; 0x00367548 (fixed camera position)
.word 0x00080000, 0x11012080, 0x0A000000

; 0x00367554
@link_behaviour @INTERACTIVE, beh_free_range_chomp_impl

; 0x00367560
beh_cursor:
@link_behaviour @DEFAULT, beh_cursor_impl

; 0x0036756C
beh_save_file:
@link_behaviour @SURFACE, beh_save_file_impl

; 0x00367578
@link_behaviour @MAGNETIC, beh_vine_impl

; 0x00367584
@link_behaviour @SURFACE, beh_grotto_hole_impl

; 0x00367590
@link_behaviour @SPAWNER, beh_rapids_controller_impl

; 0x0036759C
@link_behaviour @SURFACE, beh_barrel_1_impl

; 0x003675A8
@link_behaviour @DEFAULT, beh_temple_water_level_impl

; 0x003675B4
@link_behaviour @SURFACE, beh_gate_switch_impl

; 0x003675C0
@link_behaviour @GENERIC, beh_key_chest_impl

; 0x003675CC
@link_behaviour @SURFACE, beh_locked_door_impl

; 0x003675D8
@link_behaviour @DEFAULT, beh_underwater_impl

; 0x003675E4
@link_behaviour @SPAWNER, beh_bubba_wrangler_impl

; 0x003675F0
@link_behaviour @GENERIC, beh_water_mine_impl

; 0x803675FC
J make_slightly_transparent
NOP :: NOP

; 0x00367608
@link_behaviour @SURFACE, beh_slab_impl

; 0x00367614
@link_behaviour @SPAWNER, beh_waterfall_platform_spawner_impl

; 0x00367620
@link_behaviour @DEFAULT, beh_temple_water_sounds_impl

; 0x0036762C
@link_behaviour @GENERIC, beh_item_chest_impl

; 0x00367638
@link_behaviour @SPAWNER, beh_sawblade_spawner_impl

; 0x00367644
@link_behaviour @SURFACE, beh_machine_boss_impl

; 0x00367650
.definelabel beh_machine_boss_floor, (org() - 0x80000000)
@link_behaviour @SURFACE, beh_machine_boss_floor_impl

; 0x0036765C
@link_behaviour @SURFACE, beh_water_temple_instant_warp_impl

; 0x00367668
.definelabel beh_life_shroom, (org() - 0x80000000)
@link_behaviour @LEVEL, beh_life_shroom_impl

; 0x00367674
@link_behaviour @LEVEL, beh_talisman_impl

; 0x00367680
@link_behaviour @LEVEL, beh_slide_goal_impl

; 0x0036768C
@link_behaviour @LEVEL, beh_skull_bomb_impl

; 0x00367698
@link_behaviour @SURFACE, beh_slide_fall_timer_impl

; 0x003676A4
@link_behaviour @SURFACE, beh_slide_gate_impl

; 0x003676B0
@link_behaviour @LEVEL, beh_poe_impl

; 0x003676BC
@link_behaviour @SURFACE, beh_toad_house_intact_impl

; 0x003676C8
@link_behaviour @SURFACE, beh_toad_house_damaged_impl

; 0x003676D4
@link_behaviour @SURFACE, beh_toad_house_razed_impl

; 0x003676E0
.definelabel beh_smoke_spawner, (org() - 0x80000000)
@link_behaviour @SPAWNER, beh_smoke_spawner_impl

; 0x003676EC
@link_behaviour @LEVEL, beh_fire_impl

; 0x003676F8
@link_behaviour @GENERIC, beh_bombiwa_impl

; 0x00367704
@link_behaviour @SPAWNER, beh_bamboo_spawner_impl

; 0x00367710
@link_behaviour @SURFACE, beh_torii_impl

; 0x0036771C
@link_behaviour @LEVEL, beh_warp_impl

; 0x00367728
@link_behaviour @SPAWNER, beh_whisp_impl

; 0x00367734
@link_behaviour @SURFACE, beh_sand_block_impl

; 0x00367740
@link_behaviour @SURFACE, beh_boo_platform_impl

; 0x0036774C
@link_behaviour @SURFACE, beh_nail_impl

; 0x00367758
@link_behaviour @SURFACE, beh_rotating_block_impl

; 0x00367764
@link_behaviour @SURFACE, beh_spinning_object_impl

; 0x00367770
@link_behaviour @SURFACE, beh_wooden_cog_impl

; 0x0036777C
@link_behaviour @SURFACE, beh_sunshine_cube_impl

; 0x00367788
@link_behaviour @LEVEL, beh_feather_impl

; 0x00367794
@link_behaviour @SPAWNER, beh_flipping_platform_spawner_impl

; 0x003677A0
.definelabel beh_warp_star_coloured, (org() - 0x80000000)
@link_behaviour @LEVEL, beh_warp_star_coloured_impl

; 0x003677AC
@link_behaviour @DEFAULT, beh_warp_unlock_impl

; 0x003677B8
@link_behaviour @SPAWNER, beh_vivian_trigger_impl

; 0x003677C4
.definelabel beh_blaarg, (org() - 0x80000000)
@link_behaviour @GENERIC, beh_blaarg_impl

; 0x003677D0
@link_behaviour @SURFACE, beh_sinking_platform_impl

; 0x003677DC
@link_behaviour @SURFACE, beh_metal_lava_platform_impl

; 0x003677E8
@link_behaviour @SURFACE, beh_barrel_2_impl

; 0x003677F4
@link_behaviour @SURFACE, beh_stalactite_large_impl

; 0x00367800
@link_behaviour @DEFAULT, beh_chain_impl

; 0x0036780C
@link_behaviour @SPAWNER, beh_fast_bomb_spawner_impl

; 0x00367818
@link_behaviour @SPAWNER, beh_blaarg_spawner_impl

; 0x00367824
@link_behaviour @SURFACE, beh_floating_platform_impl

; 0x00367830
@link_behaviour @SURFACE, beh_cracked_pillar_impl

; 0x0036783C
@link_behaviour @SURFACE, beh_stepping_stone_impl

; 0x00367848
@link_behaviour @SPAWNER, beh_fakeout_boss_impl

; 0x00367854
@link_behaviour @SURFACE, beh_fire_boss_warp_trigger_impl

; 0x00367860
@link_behaviour @SPAWNER, beh_moldorm_controller_impl

; 0x0036786C
@link_behaviour @LEVEL, beh_warp_star_item_impl

; 0x00367878
@link_behaviour @SPAWNER, beh_final_boss_trigger_impl

; 0x00367884
.definelabel beh_bowser, (org() - 0x80000000)
@link_behaviour @GENERIC, beh_bowser_impl

; 0x00367890
@link_behaviour @SPAWNER, beh_crenellation_spawner_impl

; 0x0036789C
@link_behaviour @DEFAULT, beh_flower_impl

; 0x003678A8
@link_behaviour @SPAWNER, beh_sequence_break_trigger_impl
