/*
This file was autogenerated by Bowser's Blueprint. Do not modify the file, as
contents will be overwritten next time you build.
*/


.orga 63561852
LUI T0, hi( bbp_custom_camera_init_table - 0x48 )
ORI T0, T0, lo( bbp_custom_camera_init_table - 0x48 )
