/*
This skeleton was autogenerated by Bowser's Blueprints. It will NOT be replaced
on rebuilding, so you are free to modify this file.

Do NOT use the .org, .orga, or .headersize commands in this file or files
included by this file. Anything that needs to write to elsewhere in the ROM
should go into globals.asm instead.

This file is a place to put your helper functions or code that doesn't fall
under any of the other code hooks. Code placed in this file is placed into free
space in RAM.
*/

act_nop_impl:
JR RA
MOVE V0, R0

has_pegasus_boots:
LBU V0, (global_vars + gv_items)
JR RA
ANDI V0, V0, ITEM_BOOTS

.include "./main/ui-util.asm"
.include "./main/ui-health.asm"
.include "./main/ui-pause.asm"
.include "./main/ui-keys.asm"

.include "./main/act-impaled.asm"

.include "./main/util.asm"
.include "./main/globals-data.asm"
.include "./main/save-file.asm"
.include "./main/pause.asm"
.include "./main/double-jump.asm"
.include "./main/cutscene.asm"
.include "./main/camera.asm"
.include "./main/billboard.asm"
.include "./main/bomb.asm"
.include "./main/health.asm"
.include "./main/inertia.asm"
.include "./main/drop-object.asm"

.include "./main/river.asm"
.include "./main/warp-music-fade-shim.asm"
.include "./main/ceiling-fix.asm"
.include "./main/mario-idle-shim.asm"

.include "./main/actors/warp-star.asm"
.include "./main/actors/warp-star-2.asm"
.include "./main/actors/shroom.asm"
.include "./main/actors/tree.asm"
.include "./main/actors/ghost.asm"
.include "./main/actors/chomp.asm"
.include "./main/actors/vine.asm"
.include "./main/actors/grotto-hole.asm"
.include "./main/actors/rapids-controller.asm"
.include "./main/actors/barrel.asm"
.include "./main/actors/temple-water-level.asm"
.include "./main/actors/gate-switch.asm"
.include "./main/actors/chest.asm"
.include "./main/actors/locked-door.asm"
.include "./main/actors/underwater.asm"
.include "./main/actors/bubba-wrangler.asm"
.include "./main/actors/water-mine.asm"
.include "./main/actors/slab.asm"
.include "./main/actors/waterfall-platform-spawner.asm"
.include "./main/actors/temple-water-sounds.asm"
.include "./main/actors/item-chest.asm"
.include "./main/actors/sawblade-spawner.asm"
.include "./main/actors/temple-warp.asm"
.include "./main/actors/machine-boss.asm"
.include "./main/actors/talisman.asm"
.include "./main/actors/slide-goal.asm"
.include "./main/actors/skull-bomb.asm"
.include "./main/actors/slide-fall-timer.asm"
.include "./main/actors/slide-gate.asm"
.include "./main/actors/poe.asm"
.include "./main/actors/toad-house.asm"
.include "./main/actors/smoke-spawner.asm"
.include "./main/actors/bombiwa.asm"
.include "./main/actors/bamboo.asm"
.include "./main/actors/torii.asm"
.include "./main/actors/warp.asm"
.include "./main/actors/whisp.asm"
.include "./main/actors/sand-block.asm"
.include "./main/actors/boo-ring.asm"
.include "./main/actors/nail.asm"
.include "./main/actors/rotating-block.asm"
.include "./main/actors/spinning-object.asm"
.include "./main/actors/wooden-cog.asm"
.include "./main/actors/sunshine-cube.asm"
.include "./main/actors/feather.asm"
.include "./main/actors/flipping-platform.asm"
.include "./main/actors/warp-unlock.asm"
.include "./main/actors/vivian.asm"
.include "./main/actors/blaarg.asm"
.include "./main/actors/sinking-platform.asm"
.include "./main/actors/metal-lava-platform.asm"
.include "./main/actors/stalactite.asm"
.include "./main/actors/chain.asm"
.include "./main/actors/fast-bomb-spawner.asm"
.include "./main/actors/blaarg-spawner.asm"
.include "./main/actors/floating-platform.asm"
.include "./main/actors/cracked-pillar.asm"
.include "./main/actors/stepping-stone.asm"
.include "./main/actors/fakeout-boss.asm"
.include "./main/actors/fire-boss-warp-trigger.asm"
.include "./main/actors/moldorm.asm"
.include "./main/actors/warp-star-item.asm"
.include "./main/actors/final-boss-trigger.asm"
.include "./main/actors/bowser.asm"
.include "./main/actors/crenellation.asm"

.include "./main/game-ogre.asm"
.include "./main/file-select.asm"
.include "./main/emulator-check.asm"
.include "./main/end-screen.asm"

make_slightly_transparent:
BEQ A0, R0, @@skip
LW T0, 0x8032DF04
BEQ T0, R0, @@load_other
NOP
	B @@set_opacity
	LW T0, 0x1C (T0)
@@load_other:
LW T0, 0x8032DF00
@@set_opacity:
SETU T1, 0xBF
J 0x8029D924
SW T1, o_opacity (T0)
@@skip:
J 0x8029D924
NOP

mario_fire_invinvibility_shim:
SETU AT, 45
J set_mario_action
SH AT, m_iframes (A0)

.definelabel water_mist_shim, (org() - 0x80000000)
BHV_SET_FLOAT o_render_distance, 0x7FFF
BHV_STORE_HOME
BHV_SET_INT o_face_angle_pitch, 0xC000
BHV_JUMP 0x13000DE8
