/*
This skeleton was autogenerated by Bowser's Blueprints. It will NOT be replaced
on rebuilding, so you are free to modify this file.

Do NOT use the .org, .orga, or .headersize commands in this file or files
included by this file. Anything that needs to write to elsewhere in the ROM
should go into globals.asm instead.

The code in this file will run when you enter a new area. The memory holding the
current area index is updated with the new area at this point.

NOTE: This code runs BEFORE on-level-load when loading a new level.
*/

ADDIU SP, SP, 0xFFE8
SW RA, 0x14 (SP)

LUI AT, 0x8033
LH A0, 0xDDF8 (AT)
LUI AT, 0x8034
LH A1, 0xBAC6 (AT)
LH A2, 0xBACA (AT)

; A0 = current level ID
; A1 = current course number
; A2 = current area index

; Your code goes here
;LW T0, (g_mario + 0x88)
;SW T0, g_mario_obj_ptr

LW RA, 0x14 (SP)
JR RA
ADDIU SP, SP, 0x18
