/*
This skeleton was autogenerated by Bowser's Blueprints. It will NOT be replaced
on rebuilding, so you are free to modify this file.

Do NOT use the .org, .orga, or .headersize commands in this file or files
included by this file. Anything that needs to write to elsewhere in the ROM
should go into globals.asm instead.

The code in this file will run every frame just before the buffer swap.
*/

ADDIU SP, SP, 0xFFE8
SW RA, 0x14 (SP)
SW A0, 0x10 (SP)

JAL manage_bamboo
NOP

LW A0, 0x10 (SP) ; !Important: don't remove this
LW RA, 0x14 (SP)
JR RA
ADDIU SP, SP, 0x18
