/*
This skeleton was autogenerated by Bowser's Blueprints. It will NOT be replaced
on rebuilding, so you are free to modify this file.

The code in this file will run just after the HUD renders. Your code that adds
custom UI elements should go here.

Do NOT use the .org, .orga, or .headersize commands in this file or files
included by this file. Anything that needs to write to elsewhere in the ROM
should go into globals.asm instead.

NOTE: If you have a lot of Fast3D commands to run, you should put them in a
display list, then add a single command to the master display list to execute
your display list instead of appending everything to the master display list
directly. Otherwise, you could potentially overflow the master display list.
*/

ADDIU SP, SP, 0xFFE8
SW RA, 0x14 (SP)

; Your code goes here
JAL render_health
NOP

JAL render_talisman_metre
NOP

JAL game_ogre_render
NOP

JAL file_select_render
NOP

JAL render_emulator_check
NOP

JAL render_warp_destination
NOP

JAL render_warp_unlock_message
NOP

JAL render_pause_screen
NOP

JAL render_end_screen
NOP

LW RA, 0x14 (SP)
JR RA
ADDIU SP, SP, 0x18
