/*
This skeleton was autogenerated by Bowser's Blueprints. It will NOT be replaced
on rebuilding, so you are free to modify this file.

Do NOT use the .org, .orga, or .headersize commands in this file or files
included by this file. Anything that needs to write to elsewhere in the ROM
should go into globals.asm instead.

The code in this file will run when you begin a level. The memory holding the
current level, course, and area hold the values for the new level at this point.
*/

ADDIU SP, SP, 0xFFE8
SW RA, 0x14 (SP)

LUI AT, 0x8033
LH A0, 0xDDF8 (AT)
LUI AT, 0x8034
LH A1, 0xBAC6 (AT)
LH A2, 0xBACA (AT)

; A0 = current level ID
; A1 = current course number
; A2 = current area index

; Your code goes here
SW R0, dead_chomp_flags
SB R0, 0x8032DA98

LHU T0, g_level_num
SETU AT, 0x1A
BEQ T0, AT, @handle_game_over
SETU AT, 0x14
BEQ T0, AT, @handle_file_select
SETU AT, 0x1B
BEQ T0, AT, @handle_emulator_check
SETU AT, 0x1F
BEQ T0, AT, @handle_end_screen
LH T1, g_level_num
SH T1, (global_vars + sv_level)
@done_special_level_handling:

LUI A0, 0x0403
JAL segmented_to_virtual
ORI A0, A0, 0x2A48

LHU T0, g_level_num
SETU AT, 0x17
LUI T1, 0xFFFF
BNE AT, T0, @@endif_bamboo_forest
ORI T1, T1, 0x64FF
	LI T1, 0x0CA6CDFF
@@endif_bamboo_forest:
SW T1, 0x0C (V0)
SW T1, 0x1C (V0)
SW T1, 0x2C (V0)
SW T1, 0x3C (V0)

LW RA, 0x14 (SP)
JR RA
ADDIU SP, SP, 0x18

@handle_game_over:
	JAL game_ogre_init
	NOP
	B @done_special_level_handling
	NOP

@handle_file_select:
	JAL file_select_init
	NOP
	B @done_special_level_handling
	NOP
	
@handle_emulator_check:
	JAL emulator_check_init
	NOP
	B @done_special_level_handling
	NOP
	
@handle_end_screen:
	JAL end_screen_init
	NOP
	B @done_special_level_handling
	NOP
