/*
This skeleton was autogenerated by Bowser's Blueprints. It will NOT be replaced
on rebuilding, so you are free to modify this file.

Do NOT use the .org, .orga, or .headersize commands in this file or files
included by this file. Anything that needs to write to elsewhere in the ROM
should go into globals.asm instead.

The code in this file will run just after Mario's behaviour script is run.
*/

ADDIU SP, SP, 0xFFE8
SW RA, 0x14 (SP)

LI A0, 0x8033B170
LW A1, 0x80361158

; A0 = Mario struct pointer
; A1 = Mario object pointer

; Mario is always at full health while on Star Road
LHU T0, g_level_num
SETU AT, 0x10
BNE T0, AT, @@endif_star_road
	LHU T0, (global_vars + gv_max_health)
	SH T0, m_health (A0)
@@endif_star_road:

JAL check_restore_double_jump
NOP

; The unused forward flip animation has Mario backwards. Fix this.
LI T0, g_mario
LW T1, 0xA0 (T0)
LW T1, 0x4 (T1)
LI AT, 0x00527248
BNE T1, AT, @@endif_forward_flip
	LHU T0, m_angle_yaw (T0)
	ADDIU T0, T0, 0x8000
	ANDI T0, T0, 0xFFFF
	LW T1, g_mario_obj_ptr
	SH T0, o_gfx_angle_yaw (T1)
@@endif_forward_flip:

JAL process_river_current
NOP

JAL check_rapids_warp
NOP

JAL handle_inertia
NOP

; Void out from lava
LI T0, g_mario
LW T1, m_action (T0)
LI T2, 0x010208B7
BNE T1, T2, @@endif_lava_void
	LHU AT, m_health (T0)
	SLTIU AT, AT, 0x300
	BEQ AT, R0, @@endif_dead
		SETU AT, 8
		B @@endif_lava_void
		SB AT, m_hurt_counter (T0)
	@@endif_dead:
	JAL bbp_9f5317da4fb645b89267ec1bc50d9aad_void_out
	MOVE A0, T0
@@endif_lava_void:

LW RA, 0x14 (SP)
JR RA
ADDIU SP, SP, 0x18
