/*
This skeleton was autogenerated by Bowser's Blueprints. It will NOT be replaced
on rebuilding, so you are free to modify this file.

Do NOT use the .org, .orga, or .headersize commands in this file or files
included by this file. Anything that needs to write to elsewhere in the ROM
should go into globals.asm instead.

The code in this file will run just before Mario's behaviour script is run.
*/

ADDIU SP, SP, 0xFFE8
SW RA, 0x14 (SP)

LI A0, 0x8033B170
LW A1, 0x80361158

; A0 = Mario struct pointer
; A1 = Mario object pointer

LW T0, m_action (A0)
SW T0, mario_action_on_frame_start

JAL handle_spikes
NOP

LW RA, 0x14 (SP)
JR RA
ADDIU SP, SP, 0x18

mario_action_on_frame_start:
.word 0
